### ISSUE TITLE
Quick issue to change the blank.png link to your repo's raw link.

### ISSUE THREAD

**Issue by ggppjj** [ctrezevant/eliteshell#6]
blank.png reference should be https://raw.github.com/ctrezevant/eliteshell/blob/master/blank.png

Happy New Year!

**Comment by chtzvt** [comment]
Unfortunately, Reddit only allows you to use images that you've uploaded in the CSS editor (see [here](https://www.reddit.com/r/csshelp/comments/nia9f/external_image_url_in_subreddit_css_stylesheet/)), so I don't think this would work. Unless I've misunderstood?

**Comment by ggppjj** [comment]
You have. I meant the github project's page. The blank.png currently
directs to my repo's blank png.

**Comment by chtzvt** [comment]
Ah, I see. All fixed!
