### ISSUE TITLE
The DOS prompt is missing its backslash!

### ISSUE THREAD

**Issue by ggppjj** [ctrezevant/eliteshell#7]
If you use this exact character, you will get a backslash that the CSS parser allows through its checks:

∖

It's a math symbol that means something or other. Specifically, it should go in the subscribers text, as so: C:∖>

Magic Backslash Ahoy!

**Comment by chtzvt** [comment]
Nice find! 

I plan to make a wiki for eliteshell at some point, and this will definitely be going in there.
