### ISSUE TITLE
No way to discern links in posts

### ISSUE THREAD

**Issue by the-white-light** [ctrezevant/eliteshell#8]
In [this post](http://i.imgur.com/41HjGMR.png) there's no way to tell where the links are without actually hovering over each word. Links show up fine [elsewhere](http://i.imgur.com/TB0D8mv.png) such as the sidebar.

**Comment by chtzvt** [comment]
Nice catch! I've removed the [offending line](https://github.com/ctrezevant/eliteshell/blob/c14bc039d390d895f94e27e412da1ebb10626de7/eliteshell.css#L64) and the issue appears to have been fixed :+1:

Thanks for contributing!
